config = {
  :box          => 'centos-vm-7.2',
}

nodes = [
  {
    :name => 'node1',
    :cpus     => '2',
    :memory   => '2048',
    :box      => config[:box]
  },
  {
    :name => 'node2',
    :cpus     => '2',
    :memory   => '2048',
    :box      => config[:box]
  },
  {
    :name => 'node3',
    :cpus     => '2',
    :memory   => '2048',
    :box      => config[:box]
   }
]

Vagrant.configure("2") do |cfg|
  nodes.each do |node|
   cfg.vm.define node[:name] do |node_config|
      node_config.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = node[:memory]
        v.vmx["numvcpus"] = node[:cpus]
      end
     node_config.vm.provision "file", run: "always", source: "../file/authorized_keys", destination: "/tmp/authorized_keys"
     node_config.vm.provision "shell", run: "always", inline: <<-SHELL
          mkdir -p /root/.ssh/ && cat /tmp/authorized_keys > /root/.ssh/authorized_keys
     SHELL

     node_config.vm.network :private_network
     node_config.vm.host_name = node[:name]
     node_config.vm.box = node[:box]
    end
  end
end